version: '3'
services:
  main:
    build: .
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: haskell 
      POSTGRES_USER: haskell
      POSTGRES_DB: crm
